"$schema" = 'https://raw.githubusercontent.com/yazi-rs/schemas/refs/heads/main/schemas/keymap.json'

[[manager.prepend_keymap]]
on = ["g", "r"]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'
