return {
  "williamboman/mason.nvim",
  cmd = "Mason",
  keys = { { "<leader>cm", "<cmd>Mason<cr>", desc = "Mason" } },
  build = ":MasonUpdate",
  opts = {
    ensure_installed = {
      "bash-language-server",
      "biome",
      "codelldb",
      "docker-compose-language-service",
      "dockerfile-language-server",
      "eslint-lsp",
      "gopls",
      "hadolint",
      "jdtls",
      "jq",
      "json-lsp",
      "lua-language-server",
      "markdownlint",
      "marksman",
      "pyright",
      "quick-lint-js",
      "ruff-lsp",
      "rust-analyzer",
      "shfmt",
      "sql-formatter",
      "sqlfmt",
      "stylua",
      "svelte-language-server",
      "tailwindcss-language-server",
      "taplo",
      "terraform-ls",
      "typescript-language-server",
      "yaml-language-server",
    },
  },
}
